[2025-01-15 15:31:19,004] {processor.py:153} INFO - Started process (PID=82635) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:19,005] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:31:19,006] {logging_mixin.py:115} INFO - [2025-01-15 15:31:19,006] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:19,013] {logging_mixin.py:115} INFO - [2025-01-15 15:31:19,011] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:31:19,014] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:19,050] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.054 seconds
[2025-01-15 15:31:50,100] {processor.py:153} INFO - Started process (PID=82772) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:50,100] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:31:50,101] {logging_mixin.py:115} INFO - [2025-01-15 15:31:50,101] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:50,103] {logging_mixin.py:115} INFO - [2025-01-15 15:31:50,102] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:31:50,105] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:31:50,127] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.030 seconds
[2025-01-15 15:32:20,311] {processor.py:153} INFO - Started process (PID=82843) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:32:20,312] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:32:20,313] {logging_mixin.py:115} INFO - [2025-01-15 15:32:20,313] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:32:20,315] {logging_mixin.py:115} INFO - [2025-01-15 15:32:20,315] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:32:20,315] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:32:20,328] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.019 seconds
[2025-01-15 15:34:35,906] {processor.py:153} INFO - Started process (PID=2919) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:34:35,908] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:34:35,908] {logging_mixin.py:115} INFO - [2025-01-15 15:34:35,908] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:34:35,911] {logging_mixin.py:115} INFO - [2025-01-15 15:34:35,910] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:34:35,911] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:34:35,927] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.024 seconds
[2025-01-15 15:35:06,021] {processor.py:153} INFO - Started process (PID=3600) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:06,022] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:35:06,022] {logging_mixin.py:115} INFO - [2025-01-15 15:35:06,022] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:06,024] {logging_mixin.py:115} INFO - [2025-01-15 15:35:06,023] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:35:06,024] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:06,036] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:35:36,303] {processor.py:153} INFO - Started process (PID=3645) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:36,304] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:35:36,304] {logging_mixin.py:115} INFO - [2025-01-15 15:35:36,304] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:36,306] {logging_mixin.py:115} INFO - [2025-01-15 15:35:36,305] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:35:36,306] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:35:36,317] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 15:36:06,572] {processor.py:153} INFO - Started process (PID=3657) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:06,573] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:36:06,573] {logging_mixin.py:115} INFO - [2025-01-15 15:36:06,573] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:06,575] {logging_mixin.py:115} INFO - [2025-01-15 15:36:06,574] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:36:06,575] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:06,586] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:36:36,844] {processor.py:153} INFO - Started process (PID=3658) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:36,845] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:36:36,845] {logging_mixin.py:115} INFO - [2025-01-15 15:36:36,845] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:36,846] {logging_mixin.py:115} INFO - [2025-01-15 15:36:36,846] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:36:36,847] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:36:36,858] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:37:07,112] {processor.py:153} INFO - Started process (PID=3659) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:07,113] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:37:07,113] {logging_mixin.py:115} INFO - [2025-01-15 15:37:07,113] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:07,115] {logging_mixin.py:115} INFO - [2025-01-15 15:37:07,114] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:37:07,115] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:07,127] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:37:37,300] {processor.py:153} INFO - Started process (PID=3664) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:37,301] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:37:37,301] {logging_mixin.py:115} INFO - [2025-01-15 15:37:37,301] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:37,302] {logging_mixin.py:115} INFO - [2025-01-15 15:37:37,302] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:37:37,303] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:37:37,316] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:38:07,571] {processor.py:153} INFO - Started process (PID=3665) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:07,572] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:38:07,572] {logging_mixin.py:115} INFO - [2025-01-15 15:38:07,572] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:07,574] {logging_mixin.py:115} INFO - [2025-01-15 15:38:07,573] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:38:07,574] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:07,585] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:38:37,841] {processor.py:153} INFO - Started process (PID=3670) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:37,842] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:38:37,842] {logging_mixin.py:115} INFO - [2025-01-15 15:38:37,842] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:37,844] {logging_mixin.py:115} INFO - [2025-01-15 15:38:37,843] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:38:37,844] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:38:37,855] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:39:08,113] {processor.py:153} INFO - Started process (PID=3675) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:08,114] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:39:08,114] {logging_mixin.py:115} INFO - [2025-01-15 15:39:08,114] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:08,116] {logging_mixin.py:115} INFO - [2025-01-15 15:39:08,115] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:39:08,116] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:08,128] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:39:38,401] {processor.py:153} INFO - Started process (PID=3736) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:38,401] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:39:38,402] {logging_mixin.py:115} INFO - [2025-01-15 15:39:38,402] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:38,403] {logging_mixin.py:115} INFO - [2025-01-15 15:39:38,403] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:39:38,403] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:39:38,417] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:40:08,669] {processor.py:153} INFO - Started process (PID=3741) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:08,670] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:40:08,670] {logging_mixin.py:115} INFO - [2025-01-15 15:40:08,670] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:08,672] {logging_mixin.py:115} INFO - [2025-01-15 15:40:08,671] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:40:08,672] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:08,684] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:40:38,943] {processor.py:153} INFO - Started process (PID=3750) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:38,944] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:40:38,944] {logging_mixin.py:115} INFO - [2025-01-15 15:40:38,944] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:38,946] {logging_mixin.py:115} INFO - [2025-01-15 15:40:38,945] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:40:38,946] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:40:38,958] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:41:09,215] {processor.py:153} INFO - Started process (PID=3758) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:09,216] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:41:09,216] {logging_mixin.py:115} INFO - [2025-01-15 15:41:09,216] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:09,217] {logging_mixin.py:115} INFO - [2025-01-15 15:41:09,217] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:41:09,218] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:09,229] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 15:41:39,482] {processor.py:153} INFO - Started process (PID=3760) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:39,483] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:41:39,483] {logging_mixin.py:115} INFO - [2025-01-15 15:41:39,483] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:39,485] {logging_mixin.py:115} INFO - [2025-01-15 15:41:39,484] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:41:39,485] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:41:39,497] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:42:09,750] {processor.py:153} INFO - Started process (PID=3761) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:09,751] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:42:09,751] {logging_mixin.py:115} INFO - [2025-01-15 15:42:09,751] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:09,753] {logging_mixin.py:115} INFO - [2025-01-15 15:42:09,752] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:42:09,753] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:09,765] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:42:40,030] {processor.py:153} INFO - Started process (PID=3841) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:40,030] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:42:40,031] {logging_mixin.py:115} INFO - [2025-01-15 15:42:40,031] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:40,033] {logging_mixin.py:115} INFO - [2025-01-15 15:42:40,032] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:42:40,033] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:42:40,054] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.027 seconds
[2025-01-15 15:43:10,307] {processor.py:153} INFO - Started process (PID=3844) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:10,308] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:43:10,308] {logging_mixin.py:115} INFO - [2025-01-15 15:43:10,308] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:10,310] {logging_mixin.py:115} INFO - [2025-01-15 15:43:10,310] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:43:10,310] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:10,323] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:43:40,579] {processor.py:153} INFO - Started process (PID=3851) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:40,580] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:43:40,580] {logging_mixin.py:115} INFO - [2025-01-15 15:43:40,580] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:40,582] {logging_mixin.py:115} INFO - [2025-01-15 15:43:40,581] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:43:40,582] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:43:40,593] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:44:10,850] {processor.py:153} INFO - Started process (PID=3852) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:10,851] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:44:10,851] {logging_mixin.py:115} INFO - [2025-01-15 15:44:10,851] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:10,853] {logging_mixin.py:115} INFO - [2025-01-15 15:44:10,853] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:44:10,853] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:10,865] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:44:41,119] {processor.py:153} INFO - Started process (PID=3906) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:41,120] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:44:41,120] {logging_mixin.py:115} INFO - [2025-01-15 15:44:41,120] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:41,122] {logging_mixin.py:115} INFO - [2025-01-15 15:44:41,121] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:44:41,122] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:44:41,134] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:45:11,388] {processor.py:153} INFO - Started process (PID=3910) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:11,389] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:45:11,389] {logging_mixin.py:115} INFO - [2025-01-15 15:45:11,389] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:11,391] {logging_mixin.py:115} INFO - [2025-01-15 15:45:11,390] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:45:11,391] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:11,405] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.019 seconds
[2025-01-15 15:45:41,657] {processor.py:153} INFO - Started process (PID=3911) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:41,658] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:45:41,658] {logging_mixin.py:115} INFO - [2025-01-15 15:45:41,658] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:41,659] {logging_mixin.py:115} INFO - [2025-01-15 15:45:41,659] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:45:41,660] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:45:41,671] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:46:11,923] {processor.py:153} INFO - Started process (PID=3913) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:11,924] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:46:11,924] {logging_mixin.py:115} INFO - [2025-01-15 15:46:11,924] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:11,925] {logging_mixin.py:115} INFO - [2025-01-15 15:46:11,925] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:46:11,926] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:11,937] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 15:46:42,192] {processor.py:153} INFO - Started process (PID=3914) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:42,193] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:46:42,193] {logging_mixin.py:115} INFO - [2025-01-15 15:46:42,193] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:42,195] {logging_mixin.py:115} INFO - [2025-01-15 15:46:42,194] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:46:42,195] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:46:42,206] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:47:12,461] {processor.py:153} INFO - Started process (PID=3916) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:12,461] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:47:12,462] {logging_mixin.py:115} INFO - [2025-01-15 15:47:12,462] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:12,463] {logging_mixin.py:115} INFO - [2025-01-15 15:47:12,463] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:47:12,463] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:12,477] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:47:42,730] {processor.py:153} INFO - Started process (PID=3918) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:42,731] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:47:42,731] {logging_mixin.py:115} INFO - [2025-01-15 15:47:42,731] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:42,733] {logging_mixin.py:115} INFO - [2025-01-15 15:47:42,732] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:47:42,733] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:47:42,746] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:48:12,999] {processor.py:153} INFO - Started process (PID=3919) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:12,999] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:48:12,999] {logging_mixin.py:115} INFO - [2025-01-15 15:48:12,999] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:13,001] {logging_mixin.py:115} INFO - [2025-01-15 15:48:13,000] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:48:13,001] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:13,012] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:48:43,264] {processor.py:153} INFO - Started process (PID=3926) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:43,264] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:48:43,265] {logging_mixin.py:115} INFO - [2025-01-15 15:48:43,265] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:43,266] {logging_mixin.py:115} INFO - [2025-01-15 15:48:43,266] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:48:43,266] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:48:43,277] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 15:49:13,529] {processor.py:153} INFO - Started process (PID=3927) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:13,530] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:49:13,530] {logging_mixin.py:115} INFO - [2025-01-15 15:49:13,530] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:13,532] {logging_mixin.py:115} INFO - [2025-01-15 15:49:13,531] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:49:13,532] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:13,544] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:49:43,800] {processor.py:153} INFO - Started process (PID=3979) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:43,801] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:49:43,801] {logging_mixin.py:115} INFO - [2025-01-15 15:49:43,801] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:43,802] {logging_mixin.py:115} INFO - [2025-01-15 15:49:43,802] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:49:43,803] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:49:43,814] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:50:14,070] {processor.py:153} INFO - Started process (PID=3983) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:14,070] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:50:14,070] {logging_mixin.py:115} INFO - [2025-01-15 15:50:14,070] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:14,072] {logging_mixin.py:115} INFO - [2025-01-15 15:50:14,071] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:50:14,072] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:14,084] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:50:44,336] {processor.py:153} INFO - Started process (PID=3984) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:44,337] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:50:44,337] {logging_mixin.py:115} INFO - [2025-01-15 15:50:44,337] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:44,339] {logging_mixin.py:115} INFO - [2025-01-15 15:50:44,338] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:50:44,339] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:50:44,350] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:51:14,603] {processor.py:153} INFO - Started process (PID=3985) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:14,603] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:51:14,604] {logging_mixin.py:115} INFO - [2025-01-15 15:51:14,604] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:14,605] {logging_mixin.py:115} INFO - [2025-01-15 15:51:14,605] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:51:14,605] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:14,618] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:51:44,878] {processor.py:153} INFO - Started process (PID=3986) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:44,879] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:51:44,879] {logging_mixin.py:115} INFO - [2025-01-15 15:51:44,879] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:44,881] {logging_mixin.py:115} INFO - [2025-01-15 15:51:44,880] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:51:44,881] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:51:44,892] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:52:15,152] {processor.py:153} INFO - Started process (PID=3987) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:15,152] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:52:15,153] {logging_mixin.py:115} INFO - [2025-01-15 15:52:15,153] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:15,154] {logging_mixin.py:115} INFO - [2025-01-15 15:52:15,154] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:52:15,154] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:15,166] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:52:45,424] {processor.py:153} INFO - Started process (PID=3988) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:45,424] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:52:45,425] {logging_mixin.py:115} INFO - [2025-01-15 15:52:45,425] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:45,426] {logging_mixin.py:115} INFO - [2025-01-15 15:52:45,426] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:52:45,427] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:52:45,439] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:53:15,697] {processor.py:153} INFO - Started process (PID=3989) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:15,697] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:53:15,698] {logging_mixin.py:115} INFO - [2025-01-15 15:53:15,698] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:15,699] {logging_mixin.py:115} INFO - [2025-01-15 15:53:15,699] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:53:15,699] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:15,711] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:53:45,968] {processor.py:153} INFO - Started process (PID=3993) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:45,968] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:53:45,968] {logging_mixin.py:115} INFO - [2025-01-15 15:53:45,968] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:45,970] {logging_mixin.py:115} INFO - [2025-01-15 15:53:45,969] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:53:45,970] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:53:45,981] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 15:54:16,235] {processor.py:153} INFO - Started process (PID=3994) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:16,236] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:54:16,236] {logging_mixin.py:115} INFO - [2025-01-15 15:54:16,236] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:16,237] {logging_mixin.py:115} INFO - [2025-01-15 15:54:16,237] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:54:16,238] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:16,253] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.020 seconds
[2025-01-15 15:54:46,504] {processor.py:153} INFO - Started process (PID=4046) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:46,505] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:54:46,505] {logging_mixin.py:115} INFO - [2025-01-15 15:54:46,505] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:46,506] {logging_mixin.py:115} INFO - [2025-01-15 15:54:46,506] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:54:46,507] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:54:46,518] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 15:55:16,775] {processor.py:153} INFO - Started process (PID=4124) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:16,776] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:55:16,776] {logging_mixin.py:115} INFO - [2025-01-15 15:55:16,776] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:16,778] {logging_mixin.py:115} INFO - [2025-01-15 15:55:16,777] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:55:16,778] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:16,794] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.020 seconds
[2025-01-15 15:55:47,048] {processor.py:153} INFO - Started process (PID=4131) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:47,049] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:55:47,050] {logging_mixin.py:115} INFO - [2025-01-15 15:55:47,050] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:47,054] {logging_mixin.py:115} INFO - [2025-01-15 15:55:47,052] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:55:47,054] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:55:47,080] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.037 seconds
[2025-01-15 15:56:17,320] {processor.py:153} INFO - Started process (PID=4132) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:17,321] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:56:17,321] {logging_mixin.py:115} INFO - [2025-01-15 15:56:17,321] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:17,323] {logging_mixin.py:115} INFO - [2025-01-15 15:56:17,322] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:56:17,323] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:17,336] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:56:47,610] {processor.py:153} INFO - Started process (PID=4133) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:47,610] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:56:47,611] {logging_mixin.py:115} INFO - [2025-01-15 15:56:47,611] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:47,612] {logging_mixin.py:115} INFO - [2025-01-15 15:56:47,612] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:56:47,612] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:56:47,626] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:57:17,889] {processor.py:153} INFO - Started process (PID=4134) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:17,890] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:57:17,890] {logging_mixin.py:115} INFO - [2025-01-15 15:57:17,890] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:17,892] {logging_mixin.py:115} INFO - [2025-01-15 15:57:17,891] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:57:17,892] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:17,905] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 15:57:48,166] {processor.py:153} INFO - Started process (PID=4135) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:48,167] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:57:48,167] {logging_mixin.py:115} INFO - [2025-01-15 15:57:48,167] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:48,169] {logging_mixin.py:115} INFO - [2025-01-15 15:57:48,168] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:57:48,169] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:57:48,182] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:58:18,441] {processor.py:153} INFO - Started process (PID=4136) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:18,441] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:58:18,441] {logging_mixin.py:115} INFO - [2025-01-15 15:58:18,441] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:18,443] {logging_mixin.py:115} INFO - [2025-01-15 15:58:18,442] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:58:18,443] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:18,456] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:58:48,718] {processor.py:153} INFO - Started process (PID=4137) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:48,719] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:58:48,719] {logging_mixin.py:115} INFO - [2025-01-15 15:58:48,719] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:48,721] {logging_mixin.py:115} INFO - [2025-01-15 15:58:48,720] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:58:48,721] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:58:48,733] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:59:18,991] {processor.py:153} INFO - Started process (PID=4139) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:18,992] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:59:18,992] {logging_mixin.py:115} INFO - [2025-01-15 15:59:18,992] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:18,994] {logging_mixin.py:115} INFO - [2025-01-15 15:59:18,993] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:59:18,994] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:19,006] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 15:59:49,268] {processor.py:153} INFO - Started process (PID=4192) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:49,269] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 15:59:49,269] {logging_mixin.py:115} INFO - [2025-01-15 15:59:49,269] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:49,270] {logging_mixin.py:115} INFO - [2025-01-15 15:59:49,270] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 15:59:49,271] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 15:59:49,282] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:00:19,448] {processor.py:153} INFO - Started process (PID=4199) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:19,449] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:00:19,449] {logging_mixin.py:115} INFO - [2025-01-15 16:00:19,449] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:19,451] {logging_mixin.py:115} INFO - [2025-01-15 16:00:19,450] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:00:19,451] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:19,462] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:00:49,629] {processor.py:153} INFO - Started process (PID=4200) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:49,630] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:00:49,630] {logging_mixin.py:115} INFO - [2025-01-15 16:00:49,630] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:49,632] {logging_mixin.py:115} INFO - [2025-01-15 16:00:49,631] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:00:49,632] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:00:49,644] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:01:19,811] {processor.py:153} INFO - Started process (PID=4202) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:19,812] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:01:19,812] {logging_mixin.py:115} INFO - [2025-01-15 16:01:19,812] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:19,814] {logging_mixin.py:115} INFO - [2025-01-15 16:01:19,813] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:01:19,814] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:19,827] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:01:50,000] {processor.py:153} INFO - Started process (PID=4203) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:50,001] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:01:50,001] {logging_mixin.py:115} INFO - [2025-01-15 16:01:50,001] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:50,003] {logging_mixin.py:115} INFO - [2025-01-15 16:01:50,002] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:01:50,003] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:01:50,015] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:02:20,182] {processor.py:153} INFO - Started process (PID=4204) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:20,182] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:02:20,182] {logging_mixin.py:115} INFO - [2025-01-15 16:02:20,182] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:20,184] {logging_mixin.py:115} INFO - [2025-01-15 16:02:20,183] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:02:20,184] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:20,195] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:02:50,375] {processor.py:153} INFO - Started process (PID=4206) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:50,376] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:02:50,376] {logging_mixin.py:115} INFO - [2025-01-15 16:02:50,376] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:50,378] {logging_mixin.py:115} INFO - [2025-01-15 16:02:50,377] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:02:50,378] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:02:50,391] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:03:20,555] {processor.py:153} INFO - Started process (PID=4212) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:20,556] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:03:20,556] {logging_mixin.py:115} INFO - [2025-01-15 16:03:20,556] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:20,558] {logging_mixin.py:115} INFO - [2025-01-15 16:03:20,557] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:03:20,558] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:20,571] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:03:50,741] {processor.py:153} INFO - Started process (PID=4214) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:50,741] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:03:50,742] {logging_mixin.py:115} INFO - [2025-01-15 16:03:50,742] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:50,743] {logging_mixin.py:115} INFO - [2025-01-15 16:03:50,743] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:03:50,743] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:03:50,756] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:04:20,926] {processor.py:153} INFO - Started process (PID=4215) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:20,926] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:04:20,927] {logging_mixin.py:115} INFO - [2025-01-15 16:04:20,927] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:20,928] {logging_mixin.py:115} INFO - [2025-01-15 16:04:20,928] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:04:20,929] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:20,941] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:04:51,110] {processor.py:153} INFO - Started process (PID=4275) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:51,110] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:04:51,110] {logging_mixin.py:115} INFO - [2025-01-15 16:04:51,110] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:51,112] {logging_mixin.py:115} INFO - [2025-01-15 16:04:51,111] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:04:51,112] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:04:51,125] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:05:21,294] {processor.py:153} INFO - Started process (PID=4279) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:21,294] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:05:21,295] {logging_mixin.py:115} INFO - [2025-01-15 16:05:21,294] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:21,296] {logging_mixin.py:115} INFO - [2025-01-15 16:05:21,295] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:05:21,296] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:21,308] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:05:51,492] {processor.py:153} INFO - Started process (PID=4280) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:51,493] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:05:51,493] {logging_mixin.py:115} INFO - [2025-01-15 16:05:51,493] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:51,495] {logging_mixin.py:115} INFO - [2025-01-15 16:05:51,494] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:05:51,495] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:05:51,507] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:06:21,686] {processor.py:153} INFO - Started process (PID=4281) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:21,687] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:06:21,687] {logging_mixin.py:115} INFO - [2025-01-15 16:06:21,687] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:21,689] {logging_mixin.py:115} INFO - [2025-01-15 16:06:21,688] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:06:21,689] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:21,701] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:06:51,871] {processor.py:153} INFO - Started process (PID=4282) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:51,872] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:06:51,872] {logging_mixin.py:115} INFO - [2025-01-15 16:06:51,872] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:51,874] {logging_mixin.py:115} INFO - [2025-01-15 16:06:51,873] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:06:51,874] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:06:51,885] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:07:22,056] {processor.py:153} INFO - Started process (PID=4431) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:22,057] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:07:22,057] {logging_mixin.py:115} INFO - [2025-01-15 16:07:22,057] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:22,058] {logging_mixin.py:115} INFO - [2025-01-15 16:07:22,058] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:07:22,059] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:22,079] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.024 seconds
[2025-01-15 16:07:52,240] {processor.py:153} INFO - Started process (PID=4635) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:52,241] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:07:52,241] {logging_mixin.py:115} INFO - [2025-01-15 16:07:52,241] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:52,243] {logging_mixin.py:115} INFO - [2025-01-15 16:07:52,242] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:07:52,243] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:07:52,256] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:08:22,424] {processor.py:153} INFO - Started process (PID=4780) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:22,424] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:08:22,425] {logging_mixin.py:115} INFO - [2025-01-15 16:08:22,425] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:22,426] {logging_mixin.py:115} INFO - [2025-01-15 16:08:22,426] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:08:22,427] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:22,439] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:08:52,612] {processor.py:153} INFO - Started process (PID=4929) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:52,613] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:08:52,614] {logging_mixin.py:115} INFO - [2025-01-15 16:08:52,614] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:52,617] {logging_mixin.py:115} INFO - [2025-01-15 16:08:52,616] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:08:52,618] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:08:52,644] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.038 seconds
[2025-01-15 16:09:22,789] {processor.py:153} INFO - Started process (PID=4981) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:22,790] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:09:22,790] {logging_mixin.py:115} INFO - [2025-01-15 16:09:22,790] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:22,792] {logging_mixin.py:115} INFO - [2025-01-15 16:09:22,791] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:09:22,792] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:22,804] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:09:52,977] {processor.py:153} INFO - Started process (PID=5038) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:52,977] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:09:52,978] {logging_mixin.py:115} INFO - [2025-01-15 16:09:52,978] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:52,979] {logging_mixin.py:115} INFO - [2025-01-15 16:09:52,979] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:09:52,979] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:09:52,992] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:10:23,158] {processor.py:153} INFO - Started process (PID=5096) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:23,159] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:10:23,159] {logging_mixin.py:115} INFO - [2025-01-15 16:10:23,159] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:23,161] {logging_mixin.py:115} INFO - [2025-01-15 16:10:23,160] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:10:23,161] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:23,173] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:10:53,340] {processor.py:153} INFO - Started process (PID=5255) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:53,341] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:10:53,341] {logging_mixin.py:115} INFO - [2025-01-15 16:10:53,341] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:53,345] {logging_mixin.py:115} INFO - [2025-01-15 16:10:53,344] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:10:53,345] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:10:53,373] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.036 seconds
[2025-01-15 16:11:23,521] {processor.py:153} INFO - Started process (PID=5466) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:23,521] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:11:23,522] {logging_mixin.py:115} INFO - [2025-01-15 16:11:23,522] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:23,524] {logging_mixin.py:115} INFO - [2025-01-15 16:11:23,523] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:11:23,524] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:23,536] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:11:53,700] {processor.py:153} INFO - Started process (PID=5611) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:53,701] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:11:53,701] {logging_mixin.py:115} INFO - [2025-01-15 16:11:53,701] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:53,703] {logging_mixin.py:115} INFO - [2025-01-15 16:11:53,702] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:11:53,703] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:11:53,716] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:12:23,885] {processor.py:153} INFO - Started process (PID=5758) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:23,885] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:12:23,886] {logging_mixin.py:115} INFO - [2025-01-15 16:12:23,886] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:23,887] {logging_mixin.py:115} INFO - [2025-01-15 16:12:23,887] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:12:23,887] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:23,902] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.019 seconds
[2025-01-15 16:12:54,070] {processor.py:153} INFO - Started process (PID=5904) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:54,070] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:12:54,070] {logging_mixin.py:115} INFO - [2025-01-15 16:12:54,070] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:54,072] {logging_mixin.py:115} INFO - [2025-01-15 16:12:54,071] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:12:54,072] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:12:54,084] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:13:24,253] {processor.py:153} INFO - Started process (PID=5978) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:24,254] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:13:24,254] {logging_mixin.py:115} INFO - [2025-01-15 16:13:24,254] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:24,256] {logging_mixin.py:115} INFO - [2025-01-15 16:13:24,255] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:13:24,256] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:24,268] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:13:54,435] {processor.py:153} INFO - Started process (PID=5979) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:54,435] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:13:54,436] {logging_mixin.py:115} INFO - [2025-01-15 16:13:54,436] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:54,437] {logging_mixin.py:115} INFO - [2025-01-15 16:13:54,437] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:13:54,437] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:13:54,449] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:14:24,615] {processor.py:153} INFO - Started process (PID=5980) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:24,616] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:14:24,616] {logging_mixin.py:115} INFO - [2025-01-15 16:14:24,616] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:24,618] {logging_mixin.py:115} INFO - [2025-01-15 16:14:24,618] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:14:24,618] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:24,631] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:14:54,774] {processor.py:153} INFO - Started process (PID=6036) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:54,775] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:14:54,775] {logging_mixin.py:115} INFO - [2025-01-15 16:14:54,775] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:54,776] {logging_mixin.py:115} INFO - [2025-01-15 16:14:54,776] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:14:54,777] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:14:54,789] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:15:24,935] {processor.py:153} INFO - Started process (PID=6045) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:24,935] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:15:24,936] {logging_mixin.py:115} INFO - [2025-01-15 16:15:24,936] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:24,937] {logging_mixin.py:115} INFO - [2025-01-15 16:15:24,937] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:15:24,938] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:24,950] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:15:55,101] {processor.py:153} INFO - Started process (PID=6049) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:55,102] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:15:55,103] {logging_mixin.py:115} INFO - [2025-01-15 16:15:55,103] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:55,106] {logging_mixin.py:115} INFO - [2025-01-15 16:15:55,105] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:15:55,106] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:15:55,131] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.035 seconds
[2025-01-15 16:16:25,257] {processor.py:153} INFO - Started process (PID=6063) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:25,258] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:16:25,258] {logging_mixin.py:115} INFO - [2025-01-15 16:16:25,258] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:25,263] {logging_mixin.py:115} INFO - [2025-01-15 16:16:25,261] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:16:25,263] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:25,297] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.047 seconds
[2025-01-15 16:16:55,416] {processor.py:153} INFO - Started process (PID=6070) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:55,417] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:16:55,417] {logging_mixin.py:115} INFO - [2025-01-15 16:16:55,417] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:55,418] {logging_mixin.py:115} INFO - [2025-01-15 16:16:55,418] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'operator.x_operator'; 'operator' is not a package
[2025-01-15 16:16:55,419] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:16:55,431] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:17:25,577] {processor.py:153} INFO - Started process (PID=6077) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:25,578] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:17:25,578] {logging_mixin.py:115} INFO - [2025-01-15 16:17:25,578] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:25,586] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:25,595] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.021 seconds
[2025-01-15 16:17:55,737] {processor.py:153} INFO - Started process (PID=6079) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:55,738] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:17:55,738] {logging_mixin.py:115} INFO - [2025-01-15 16:17:55,738] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:55,743] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:17:55,750] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:18:25,896] {processor.py:153} INFO - Started process (PID=6085) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:25,896] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:18:25,897] {logging_mixin.py:115} INFO - [2025-01-15 16:18:25,897] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:25,902] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:25,910] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:18:56,057] {processor.py:153} INFO - Started process (PID=6087) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:56,057] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:18:56,058] {logging_mixin.py:115} INFO - [2025-01-15 16:18:56,058] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:56,063] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:18:56,071] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:19:26,219] {processor.py:153} INFO - Started process (PID=6088) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:26,219] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:19:26,220] {logging_mixin.py:115} INFO - [2025-01-15 16:19:26,220] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:26,225] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:26,233] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:19:56,379] {processor.py:153} INFO - Started process (PID=6144) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:56,379] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:19:56,380] {logging_mixin.py:115} INFO - [2025-01-15 16:19:56,380] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:56,384] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:19:56,391] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:20:26,540] {processor.py:153} INFO - Started process (PID=6147) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:26,541] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:20:26,541] {logging_mixin.py:115} INFO - [2025-01-15 16:20:26,541] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:26,546] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:26,554] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:20:56,702] {processor.py:153} INFO - Started process (PID=6148) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:56,702] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:20:56,703] {logging_mixin.py:115} INFO - [2025-01-15 16:20:56,703] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:56,707] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:20:56,715] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:21:26,861] {processor.py:153} INFO - Started process (PID=6149) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:26,862] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:21:26,862] {logging_mixin.py:115} INFO - [2025-01-15 16:21:26,862] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:26,867] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:26,875] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:21:57,024] {processor.py:153} INFO - Started process (PID=6150) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:57,024] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:21:57,025] {logging_mixin.py:115} INFO - [2025-01-15 16:21:57,025] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:57,030] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:21:57,039] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:22:27,184] {processor.py:153} INFO - Started process (PID=6153) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:27,185] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:22:27,185] {logging_mixin.py:115} INFO - [2025-01-15 16:22:27,185] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:27,190] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:27,199] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:22:57,342] {processor.py:153} INFO - Started process (PID=6156) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:57,342] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:22:57,343] {logging_mixin.py:115} INFO - [2025-01-15 16:22:57,343] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:57,347] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:22:57,355] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:23:27,496] {processor.py:153} INFO - Started process (PID=6158) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:27,497] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:23:27,497] {logging_mixin.py:115} INFO - [2025-01-15 16:23:27,497] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:27,502] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:27,509] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:23:57,656] {processor.py:153} INFO - Started process (PID=6159) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:57,657] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:23:57,658] {logging_mixin.py:115} INFO - [2025-01-15 16:23:57,658] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:57,662] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:23:57,670] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:24:27,809] {processor.py:153} INFO - Started process (PID=6160) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:27,810] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:24:27,811] {logging_mixin.py:115} INFO - [2025-01-15 16:24:27,811] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:27,815] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:27,825] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:24:57,965] {processor.py:153} INFO - Started process (PID=6230) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:57,965] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:24:57,965] {logging_mixin.py:115} INFO - [2025-01-15 16:24:57,965] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:57,970] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:24:57,979] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:25:28,118] {processor.py:153} INFO - Started process (PID=6500) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:28,119] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:25:28,119] {logging_mixin.py:115} INFO - [2025-01-15 16:25:28,119] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:28,124] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:28,134] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:25:58,276] {processor.py:153} INFO - Started process (PID=6777) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:58,277] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:25:58,277] {logging_mixin.py:115} INFO - [2025-01-15 16:25:58,277] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:58,282] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:25:58,292] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:26:28,433] {processor.py:153} INFO - Started process (PID=6808) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:28,434] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:26:28,434] {logging_mixin.py:115} INFO - [2025-01-15 16:26:28,434] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:28,439] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:28,447] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:26:43,986] {processor.py:153} INFO - Started process (PID=6862) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:43,987] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:26:43,987] {logging_mixin.py:115} INFO - [2025-01-15 16:26:43,987] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:43,992] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:26:43,998] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:27:14,116] {processor.py:153} INFO - Started process (PID=7083) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:14,117] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:27:14,117] {logging_mixin.py:115} INFO - [2025-01-15 16:27:14,117] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:14,122] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:14,130] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:27:44,399] {processor.py:153} INFO - Started process (PID=7266) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:44,399] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:27:44,400] {logging_mixin.py:115} INFO - [2025-01-15 16:27:44,400] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:44,404] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:27:44,412] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:28:14,687] {processor.py:153} INFO - Started process (PID=7412) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:14,687] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:28:14,688] {logging_mixin.py:115} INFO - [2025-01-15 16:28:14,688] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:14,692] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:14,700] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:28:44,964] {processor.py:153} INFO - Started process (PID=7558) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:44,964] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:28:44,965] {logging_mixin.py:115} INFO - [2025-01-15 16:28:44,965] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:44,970] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:28:44,978] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:29:15,242] {processor.py:153} INFO - Started process (PID=7808) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:15,242] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:29:15,243] {logging_mixin.py:115} INFO - [2025-01-15 16:29:15,243] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:15,248] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:15,256] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:29:45,401] {processor.py:153} INFO - Started process (PID=7961) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:45,402] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:29:45,402] {logging_mixin.py:115} INFO - [2025-01-15 16:29:45,402] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:45,407] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:29:45,414] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:30:15,682] {processor.py:153} INFO - Started process (PID=8118) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:15,682] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:30:15,683] {logging_mixin.py:115} INFO - [2025-01-15 16:30:15,683] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:15,688] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:15,696] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:30:45,964] {processor.py:153} INFO - Started process (PID=8263) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:45,964] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:30:45,965] {logging_mixin.py:115} INFO - [2025-01-15 16:30:45,965] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:45,969] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:30:45,977] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.015 seconds
[2025-01-15 16:31:16,247] {processor.py:153} INFO - Started process (PID=8408) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:16,248] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:31:16,248] {logging_mixin.py:115} INFO - [2025-01-15 16:31:16,248] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:16,253] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:16,261] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:31:46,528] {processor.py:153} INFO - Started process (PID=8617) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:46,529] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:31:46,530] {logging_mixin.py:115} INFO - [2025-01-15 16:31:46,530] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:46,535] {logging_mixin.py:115} INFO - [2025-01-15 16:31:46,533] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from custom_operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'custom_operator'
[2025-01-15 16:31:46,535] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:31:46,566] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.040 seconds
[2025-01-15 16:32:16,781] {processor.py:153} INFO - Started process (PID=8762) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:16,782] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:32:16,782] {logging_mixin.py:115} INFO - [2025-01-15 16:32:16,782] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:16,784] {logging_mixin.py:115} INFO - [2025-01-15 16:32:16,784] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from custom_operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'custom_operator'
[2025-01-15 16:32:16,784] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:16,802] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.023 seconds
[2025-01-15 16:32:47,070] {processor.py:153} INFO - Started process (PID=8918) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:47,070] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:32:47,071] {logging_mixin.py:115} INFO - [2025-01-15 16:32:47,071] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:47,073] {logging_mixin.py:115} INFO - [2025-01-15 16:32:47,072] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from custom_operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'custom_operator'
[2025-01-15 16:32:47,073] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:32:47,087] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.021 seconds
[2025-01-15 16:33:17,349] {processor.py:153} INFO - Started process (PID=9074) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:17,350] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:33:17,351] {logging_mixin.py:115} INFO - [2025-01-15 16:33:17,351] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:17,353] {logging_mixin.py:115} INFO - [2025-01-15 16:33:17,352] {dagbag.py:320} ERROR - Failed to import: /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
Traceback (most recent call last):
  File "/home/alessandro/Documentos/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py", line 5, in <module>
    from custom_operator.x_operator import TwitterOperator
ModuleNotFoundError: No module named 'custom_operator'
[2025-01-15 16:33:17,353] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:17,366] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.019 seconds
[2025-01-15 16:33:47,637] {processor.py:153} INFO - Started process (PID=9264) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:47,637] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:33:47,637] {logging_mixin.py:115} INFO - [2025-01-15 16:33:47,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:47,644] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:33:47,655] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.020 seconds
[2025-01-15 16:34:17,927] {processor.py:153} INFO - Started process (PID=9324) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:17,928] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:34:17,928] {logging_mixin.py:115} INFO - [2025-01-15 16:34:17,928] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:17,934] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:17,944] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.020 seconds
[2025-01-15 16:34:34,669] {processor.py:153} INFO - Started process (PID=9490) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:34,670] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:34:34,670] {logging_mixin.py:115} INFO - [2025-01-15 16:34:34,670] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:34,675] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:34:34,685] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:35:04,793] {processor.py:153} INFO - Started process (PID=10056) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:04,794] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:35:04,794] {logging_mixin.py:115} INFO - [2025-01-15 16:35:04,794] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:04,799] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:04,808] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:35:35,084] {processor.py:153} INFO - Started process (PID=10166) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:35,085] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:35:35,085] {logging_mixin.py:115} INFO - [2025-01-15 16:35:35,085] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:35,090] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:35:35,098] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.016 seconds
[2025-01-15 16:36:05,379] {processor.py:153} INFO - Started process (PID=10413) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:05,380] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:36:05,380] {logging_mixin.py:115} INFO - [2025-01-15 16:36:05,380] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:05,386] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:05,395] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.018 seconds
[2025-01-15 16:36:35,676] {processor.py:153} INFO - Started process (PID=10562) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:35,676] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:36:35,677] {logging_mixin.py:115} INFO - [2025-01-15 16:36:35,677] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:35,682] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:36:35,691] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:37:05,966] {processor.py:153} INFO - Started process (PID=10707) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:05,967] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:37:05,967] {logging_mixin.py:115} INFO - [2025-01-15 16:37:05,967] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:05,972] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:05,981] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:37:36,100] {processor.py:153} INFO - Started process (PID=10708) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:36,101] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:37:36,102] {logging_mixin.py:115} INFO - [2025-01-15 16:37:36,102] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:36,107] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:37:36,115] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:38:06,425] {processor.py:153} INFO - Started process (PID=10811) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:06,425] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:38:06,426] {logging_mixin.py:115} INFO - [2025-01-15 16:38:06,426] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:06,431] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:06,439] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:38:36,700] {processor.py:153} INFO - Started process (PID=10959) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:36,701] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:38:36,701] {logging_mixin.py:115} INFO - [2025-01-15 16:38:36,701] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:36,706] {processor.py:653} WARNING - No viable dags retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:38:36,715] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.017 seconds
[2025-01-15 16:39:06,984] {processor.py:153} INFO - Started process (PID=11109) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:06,985] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:39:06,985] {logging_mixin.py:115} INFO - [2025-01-15 16:39:06,985] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:06,992] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:07,040] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,040] {manager.py:508} INFO - Created Permission View: can read on DAG:TwitterTest
[2025-01-15 16:39:07,047] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,046] {manager.py:508} INFO - Created Permission View: can edit on DAG:TwitterTest
[2025-01-15 16:39:07,051] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,051] {manager.py:508} INFO - Created Permission View: can delete on DAG:TwitterTest
[2025-01-15 16:39:07,051] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,051] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:39:07,059] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,059] {dag.py:2398} INFO - Creating ORM DAG for TwitterTest
[2025-01-15 16:39:07,066] {logging_mixin.py:115} INFO - [2025-01-15 16:39:07,066] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:39:06.990814+00:00, run_after=2025-01-16T16:39:06.990814+00:00
[2025-01-15 16:39:07,075] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.093 seconds
[2025-01-15 16:39:37,258] {processor.py:153} INFO - Started process (PID=11309) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:37,258] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:39:37,259] {logging_mixin.py:115} INFO - [2025-01-15 16:39:37,259] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:37,266] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:39:37,300] {logging_mixin.py:115} INFO - [2025-01-15 16:39:37,300] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:39:37,314] {logging_mixin.py:115} INFO - [2025-01-15 16:39:37,314] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:39:37.265067+00:00, run_after=2025-01-16T16:39:37.265067+00:00
[2025-01-15 16:39:37,324] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.068 seconds
[2025-01-15 16:40:07,496] {processor.py:153} INFO - Started process (PID=11748) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:07,497] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:40:07,497] {logging_mixin.py:115} INFO - [2025-01-15 16:40:07,497] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:07,502] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:07,533] {logging_mixin.py:115} INFO - [2025-01-15 16:40:07,533] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:40:07,543] {logging_mixin.py:115} INFO - [2025-01-15 16:40:07,543] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:40:07.501465+00:00, run_after=2025-01-16T16:40:07.501465+00:00
[2025-01-15 16:40:07,551] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.057 seconds
[2025-01-15 16:40:38,593] {processor.py:153} INFO - Started process (PID=11913) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:38,594] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:40:38,594] {logging_mixin.py:115} INFO - [2025-01-15 16:40:38,594] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:38,600] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:40:38,635] {logging_mixin.py:115} INFO - [2025-01-15 16:40:38,634] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:40:38,647] {logging_mixin.py:115} INFO - [2025-01-15 16:40:38,647] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:40:38.598751+00:00, run_after=2025-01-16T16:40:38.598751+00:00
[2025-01-15 16:40:38,656] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.066 seconds
[2025-01-15 16:41:09,700] {processor.py:153} INFO - Started process (PID=11922) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:09,701] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:41:09,702] {logging_mixin.py:115} INFO - [2025-01-15 16:41:09,702] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:09,710] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:09,746] {logging_mixin.py:115} INFO - [2025-01-15 16:41:09,746] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:41:09,759] {logging_mixin.py:115} INFO - [2025-01-15 16:41:09,759] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:41:09.708889+00:00, run_after=2025-01-16T16:41:09.708889+00:00
[2025-01-15 16:41:09,768] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.071 seconds
[2025-01-15 16:41:40,186] {processor.py:153} INFO - Started process (PID=11923) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:40,187] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:41:40,187] {logging_mixin.py:115} INFO - [2025-01-15 16:41:40,187] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:40,194] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:41:40,231] {logging_mixin.py:115} INFO - [2025-01-15 16:41:40,231] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:41:40,245] {logging_mixin.py:115} INFO - [2025-01-15 16:41:40,245] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:41:40.192181+00:00, run_after=2025-01-16T16:41:40.192181+00:00
[2025-01-15 16:41:40,254] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.070 seconds
[2025-01-15 16:42:10,482] {processor.py:153} INFO - Started process (PID=11924) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:10,483] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:42:10,483] {logging_mixin.py:115} INFO - [2025-01-15 16:42:10,483] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:10,488] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:10,523] {logging_mixin.py:115} INFO - [2025-01-15 16:42:10,523] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:42:10,537] {logging_mixin.py:115} INFO - [2025-01-15 16:42:10,537] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:42:10.487341+00:00, run_after=2025-01-16T16:42:10.487341+00:00
[2025-01-15 16:42:10,548] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.068 seconds
[2025-01-15 16:42:40,774] {processor.py:153} INFO - Started process (PID=11925) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:40,774] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:42:40,775] {logging_mixin.py:115} INFO - [2025-01-15 16:42:40,775] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:40,780] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:42:40,815] {logging_mixin.py:115} INFO - [2025-01-15 16:42:40,815] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:42:40,828] {logging_mixin.py:115} INFO - [2025-01-15 16:42:40,828] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:42:40.779626+00:00, run_after=2025-01-16T16:42:40.779626+00:00
[2025-01-15 16:42:40,837] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.065 seconds
[2025-01-15 16:43:11,077] {processor.py:153} INFO - Started process (PID=11978) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:11,078] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:43:11,078] {logging_mixin.py:115} INFO - [2025-01-15 16:43:11,078] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:11,083] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:11,115] {logging_mixin.py:115} INFO - [2025-01-15 16:43:11,115] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:43:11,125] {logging_mixin.py:115} INFO - [2025-01-15 16:43:11,125] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:43:11.082206+00:00, run_after=2025-01-16T16:43:11.082206+00:00
[2025-01-15 16:43:11,134] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.059 seconds
[2025-01-15 16:43:41,375] {processor.py:153} INFO - Started process (PID=12188) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:41,376] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:43:41,376] {logging_mixin.py:115} INFO - [2025-01-15 16:43:41,376] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:41,381] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:43:41,413] {logging_mixin.py:115} INFO - [2025-01-15 16:43:41,413] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:43:41,422] {logging_mixin.py:115} INFO - [2025-01-15 16:43:41,422] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:43:41.380458+00:00, run_after=2025-01-16T16:43:41.380458+00:00
[2025-01-15 16:43:41,431] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.058 seconds
[2025-01-15 16:44:11,674] {processor.py:153} INFO - Started process (PID=12387) to work on /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:44:11,675] {processor.py:641} INFO - Processing file /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py for tasks to queue
[2025-01-15 16:44:11,675] {logging_mixin.py:115} INFO - [2025-01-15 16:44:11,675] {dagbag.py:507} INFO - Filling up the DagBag from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:44:11,681] {processor.py:651} INFO - DAG(s) dict_keys(['TwitterTest']) retrieved from /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py
[2025-01-15 16:44:11,711] {logging_mixin.py:115} INFO - [2025-01-15 16:44:11,711] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-15 16:44:11,721] {logging_mixin.py:115} INFO - [2025-01-15 16:44:11,721] {dag.py:2927} INFO - Setting next_dagrun for TwitterTest to 2025-01-15T16:44:11.680211+00:00, run_after=2025-01-16T16:44:11.680211+00:00
[2025-01-15 16:44:11,730] {processor.py:161} INFO - Processing /home/alessandro/Documentos/airflow/airflow_pipeline/dags/x_dag.py took 0.059 seconds
